#
# EcoArmor
# by Auxilor
#

use-json: false # false = ecoarmor.yml, true = ecoarmor.json

discover-recipes: true # If all recipes should be automatically discovered.

advancement-shard-material: prismarine_shard # The material for advancement shards.
upgrade-crystal-material: end_crystal # The material for upgrade crystals.

cooldown:
  in-actionbar: true
  sound:
    enabled: true
    sound: "BLOCK_NOTE_BLOCK_PLING"
    pitch: 0.5
