#
# EcoArmor
# by Auxilor
#

discover-recipes: true # If all recipes should be automatically discovered.
update-item-names: true # If item names should be updated to match config (disable to allow renaming armor pieces in anvils)

cooldown:
  in-actionbar: true
  sound:
    enabled: true
    sound: "BLOCK_NOTE_BLOCK_PLING"
    pitch: 0.5

cannot-afford:
  in-actionbar: true
  sound:
    enabled: true
    sound: "BLOCK_NOTE_BLOCK_PLING"
    pitch: 0.5