name: EcoArmor
version: ${projectVersion}
main: com.willfp.ecoarmor.EcoArmorPlugin
api-version: 1.16
authors: [ Auxilor ]
website: willfp.com
load: STARTUP
depend:
  - eco
softdepend:
  - EcoSkills
  - AureliumSkills
  - Jobs
  - mcMMO
  - Vault

commands:
  ecoarmor:
    description: Base Command
    permission: ecoarmor.command.ecoarmor

permissions:
  ecoarmor.*:
    description: All ecoarmor permissions
    default: op
    children:
      ecoarmor.command.*: true
  ecoarmor.command.*:
    description: All commands
    default: op
    children:
      ecoarmor.command.reload: true
      ecoarmor.command.ecoarmor: true
      ecoarmor.command.give: true

  ecoarmor.command.reload:
    description: Allows reloading the config
    default: op
  ecoarmor.command.give:
    description: Allows the use of /ecoarmor give
    default: op
  ecoarmor.command.ecoarmor:
    description: Allows the user of /ecoarmor.
    default: true
