name: EcoArmor
version: ${projectVersion}
main: com.willfp.ecoarmor.EcoArmorPlugin
api-version: 1.16
authors: [ Auxilor ]
website: willfp.com
load: STARTUP
depend:
  - eco
  - ProtocolLib
softdepend:
  - WorldGuard
  - GriefPrevention
  - Towny
  - FactionsUUID
  - Lands
  - Kingdoms
  - NoCheatPlus
  - AAC
  - Matrix
  - Spartan
  - PlaceholderAPI
  - EcoEnchants

commands:
  eareload:
    description: Reloads config
    permission: ecoarmor.reload
  eagive:
    description: Give a player a set
    permission: ecoarmor.give
  eaeditor:
    description: Open the editor
    permission: ecoarmor.editor

permissions:
  ecoarmor.*:
    description: All ecoarmor permissions
    default: op
    children:
      ecoarmor.reload: true
      ecoarmor.give: true
      ecoarmor.noflydisable: true
      ecoarmor.editor: true

  ecoarmor.reload:
    description: Allows reloading the config
    default: op
  ecoarmor.give:
    description: Allows the use of /eagive
    default: op
  ecoarmor.noflydisable:
    description: Prevents losing fly.
    default: op
  ecoarmor.editor:
    description: Allows the user of /eaeditor.
    default: op
