name: EcoArmor
version: ${projectVersion}
main: com.willfp.ecoarmor.EcoArmorPlugin
api-version: 1.16
authors: [ Auxilor ]
website: willfp.com
load: STARTUP
depend:
  - ProtocolLib
softdepend:
  - WorldGuard
  - GriefPrevention
  - Towny
  - FactionsUUID
  - Lands
  - Kingdoms
  - NoCheatPlus
  - AAC
  - Matrix
  - Spartan
  - PlaceholderAPI

commands:
  eareload:
    description: Reloads config
    permission: ecoarmor.reload
  eadebug:
    description: Debug information
    permission: ecoarmor.debug
  eagive:
    description: Give a player a set
    permission: ecoarmor.give

permissions:
  ecoarmor.*:
    description: All ecoarmor permissions
    default: op
    children:
      ecoarmor.reload: true
      ecoarmor.debug: true
      ecoarmor.give: true
      ecoarmor.fromtable.*: true

  eareload.reload:
    description: Allows reloading the config
    default: op
  eareload.debug:
    description: Allows the use of /eadebug to print verbose debug information to console
    default: op
  eareload.give:
    description: Allows the use of /eagive
    default: true
  eareload.fromtable.*:
    description: Allows crafting all sets
    default: true