name: EcoArmor
version: ${projectVersion}
main: com.willfp.ecoarmor.EcoArmorPlugin
api-version: 1.16
authors: [ Auxilor ]
website: willfp.com
load: STARTUP
depend:
  - eco
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.5.21

commands:
  ecoarmor:
    description: Base Command
    permission: ecoarmor.command.ecoarmor

permissions:
  ecoarmor.*:
    description: All ecoarmor permissions
    default: op
    children:
      ecoarmor.command.*: true
      ecoarmor.noflydisable: true
  ecoarmor.command.*:
    description: All commands
    default: op
    children:
      ecoarmor.command.reload: true
      ecoarmor.command.ecoarmor: true
      ecoarmor.command.give: true
      ecoarmor.command.editor: true

  ecoarmor.command.reload:
    description: Allows reloading the config
    default: op
  ecoarmor.command.give:
    description: Allows the use of /ecoarmor give
    default: op
  ecoarmor.noflydisable:
    description: Prevents losing fly.
    default: op
  ecoarmor.command.editor:
    description: Allows the user of /ecoarmor editor.
    default: op
  ecoarmor.command.ecoarmor:
    description: Allows the user of /ecoarmor.
    default: true
